MWS_IN_MARKETPLACE_BASE_URL = 'https://mws.amazonservices.in'

MWS_IN_MARKETPLACE_ID = 'A21TJRUUN4KGV'

MWS_ORDERS_API_ENDPOINT = '/Orders/2013-09-01'

MWS_SIGNATURE_METHOD = 'HmacSHA256'

MWS_SIGNATURE_VERSION = '2'

MWS_REQUEST_METHOD = 'POST'

RK_SELLER_ID = 'A2T6OXOZIVPNRG'
