# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=254, verbose_name='Buyer Name')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonMarketPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=254)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('StandardOrder', 'Standard Order'), ('PreOrder', 'Pre Order')], default='StandardOrder', max_length=13, verbose_name='Order Type')),
                ('purchase_date', models.DateTimeField()),
                ('order_id', models.CharField(max_length=19, verbose_name='Order ID')),
                ('is_replacement_order', models.BooleanField(default=False)),
                ('replaced_order_id', models.CharField(blank=True, max_length=19, verbose_name='Replacement Order ID')),
                ('last_updated_amazon', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('number_items_shipped', models.IntegerField()),
                ('ship_service_level', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(max_length=64, verbose_name='Order Status')),
                ('fulfillment_channel', models.CharField(choices=[('MFN', 'Seller'), ('AFN', 'Fulfilled by Amazon')], default='MFN', max_length=3, verbose_name='Fulfillment Channel')),
                ('sales_channel', models.CharField(max_length=56, verbose_name='Sales Channel')),
                ('is_business_order', models.BooleanField(default=False)),
                ('earliest_ship_date', models.DateTimeField(null=True)),
                ('latest_ship_date', models.DateTimeField(null=True)),
                ('earliest_delivery_date', models.DateTimeField(null=True)),
                ('latest_delivery_date', models.DateTimeField(null=True)),
                ('number_items_unshipped', models.IntegerField()),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Rupee')], default='INR', max_length=3, verbose_name='Order Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('is_premium_order', models.BooleanField(default=False)),
                ('is_prime', models.BooleanField(default=False)),
                ('shipment_status', models.CharField(blank=True, choices=[('PendingPickUp', 'Waiting for Pickup'), ('LabelCanceled', 'Label Canceled'), ('PickedUp', 'Picked Up'), ('AtDestinationFC', 'At Destination Fulfilment Center'), ('Delivered', 'Delivered'), ('RejectedByBuyer', 'Rejected By Buyer'), ('Undeliverable', 'Undeliverable'), ('ReturnedToSeller', 'Returned To Seller')], max_length=16, verbose_name='Shipment Status')),
                ('shipment_service_level_category', models.CharField(choices=[('Standard', 'Standard'), ('Expedited', 'Expedited'), ('FreeEconomy', 'FreeEconomy'), ('NextDay', 'NextDay'), ('SameDay', 'SameDay'), ('BuyerTaxInfo', 'BuyerTaxInfo'), ('SecondDay', 'SecondDay'), ('Scheduled', 'Scheduled')], default='Standard', max_length=32, verbose_name='Shipment Service Level')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.AmazonBuyer')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.AmazonMarketPlace')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Standard', 'Standard'), ('COD', 'COD'), ('CVS', 'CVS'), ('GiftCertificate', 'Gift Certificate'), ('CreditCard', 'Credit Card'), ('Other', 'Other')], max_length=64, verbose_name='Payment Method')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.AmazonBuyer')),
            ],
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_orders', to='amazon.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='payment_methods',
            field=models.ManyToManyField(related_name='payment_method_detail_orders', to='amazon.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.ShippingAddress'),
        ),
    ]
